<a href="https://colab.research.google.com/github/msolorzan/MPU6050_PIIC/blob/master/RigidezBarra2DNodos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [61]:
import math as mt
import numpy as np
def RigidezBarra2DNodos(xi,yi,xj,yj,Em,A):
   #FUNCIÓN QUE CONSISTE EN ANALIZAR LA RIGIDEZ DE UNA BARRA CONOCIENDO SUS COORDENADAS EN i Y j
      #xi Y yi = COORDENADAS DEL NODO i
      #xj Y yj = COORDENADAS DEL NODO j
      #Em = MÓDULO DE ELASTICIDAD DEL MATERIAL
      #A = ÁREA DE LA SECCIÒN DE LA BARRA
      dx=xj-xi
      dy=yj-yi
      L=mt.sqrt(dy**2+dx**2)
      c=dx/L
      s=dy/L
      transBarra=[[c*c,c*s,-c*c,-c*s],[c*s,s*s,-c*s,-s*s],[-c*c,-c*s,c*c,c*s],[-c*s,-s*s,c*s,s*s]]
      Ke=np.dot(A*Em/L,transBarra)
      return Ke

In [63]:
Ke1=RigidezBarra2DNodos(0,0,20,0,100,1)
Ke2=RigidezBarra2DNodos(20,0,10,10,200,mt.sqrt(2))
Ke3=RigidezBarra2DNodos(0,0,10,10,200,mt.sqrt(2))
print(Ke1)
print(Ke2)
print(Ke3)

[[ 5.  0. -5.  0.]
 [ 0.  0.  0.  0.]
 [-5.  0.  5.  0.]
 [ 0.  0.  0.  0.]]
[[ 10. -10. -10.  10.]
 [-10.  10.  10. -10.]
 [-10.  10.  10. -10.]
 [ 10. -10. -10.  10.]]
[[ 10.  10. -10. -10.]
 [ 10.  10. -10. -10.]
 [-10. -10.  10.  10.]
 [-10. -10.  10.  10.]]
